name: Python mypy

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  static-analysis:
    name: Python mypy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup checkout
        uses: actions/checkout@v4
      - name: mypy
        run: |
          pip install .
          pip install --upgrade mypy
          mypy src/cellmap_data
